export const GET_ALL_CHARACTERS = 'GET_ALL_CHARACTERS'
export const LOADING_GET_ALL_CHARACTERS = 'LOADING_GET_ALL_CHARACTERS'
export const ERROR_GET_ALL_CHARACTERS = 'ERROR_GET_ALL_CHARACTERS'

export const SEARCH_CHARACTER = 'SEARCH_CHARACTER';
export const LOADING_SEARCH_CHARACTER = 'LOADING_SEARCH_CHARACTER';
export const ERROR_SEARCH_CHARACTER = 'ERROR_SEARCH_CHARACTER';

export const LOADING_GET_CHARACTER_BY_ID = 'LOADING_GET_CHARACTER_BY_ID';
export const GET_CHARACTER_BY_ID = 'GET_CHARACTER_BY_ID';
export const ERROR_GET_CHARACTER_BY_ID = 'ERROR_GET_CHARACTER_BY_ID';

export const ADD_CHARACTER_TO_LOCAL_STORAGE = 'ADD_CHARACTER_TO_LOCAL_STORAGE';
