export const GET_ALL_CHARACTERS = 'GET_ALL_CHARACTERS'
export const LOADING_GET_ALL_CHARACTERS = 'LOADING_GET_ALL_CHARACTERS'
export const ERROR_GET_ALL_CHARACTERS = 'ERROR_GET_ALL_CHARACTERS'
export const SUCCESS_GET_ALL_CHARACTERS = 'SUCCESS_GET_ALL_CHARACTERS'
